--- #YAML:1.0
name:                File-Stream
version:             2.20
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Test::More:                    0
    YAPE::Regex:                   3.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
